/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BGvZNEXtXRk
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export function home() {
  return (
    (<div
      className="flex flex-col md:flex-row items-center justify-between w-full max-w-6xl mx-auto px-4 md:px-6 py-12 md:py-24">
      <div className="flex flex-col items-start space-y-4 md:w-1/2">
        <h1 className="text-4xl md:text-5xl font-bold tracking-tighter">sendIN</h1>
        <p className="text-muted-foreground md:text-xl">The easiest way to send and receive money securely.</p>
        <div className="flex items-center space-x-4">
          <Button>Get Started</Button>
          <Link href="#" className="text-primary hover:underline" prefetch={false}>
            Learn More
          </Link>
        </div>
      </div>
      <div className="w-full md:w-1/2 mt-8 md:mt-0">
        <Card className="p-6 md:p-8">
          <CardHeader>
            <CardTitle>Payments</CardTitle>
            <CardDescription>Switch between sending and receiving money.</CardDescription>
          </CardHeader>
          <CardContent>
            <RadioGroup defaultValue="send" className="grid grid-cols-2 gap-4">
              <div>
                <RadioGroupItem value="send" id="send" className="peer sr-only" />
                <Label
                  htmlFor="send"
                  className="flex flex-col items-center justify-between rounded-md border-2 border-muted bg-popover p-4 hover:bg-accent hover:text-accent-foreground peer-data-[state=checked]:border-primary [&:has([data-state=checked])]:border-primary">
                  <SendIcon className="mb-3 h-6 w-6" />
                  Send
                </Label>
              </div>
              <div>
                <RadioGroupItem value="receive" id="receive" className="peer sr-only" />
                <Label
                  htmlFor="receive"
                  className="flex flex-col items-center justify-between rounded-md border-2 border-muted bg-popover p-4 hover:bg-accent hover:text-accent-foreground peer-data-[state=checked]:border-primary [&:has([data-state=checked])]:border-primary">
                  <ReceiptIcon className="mb-3 h-6 w-6" />
                  Receive
                </Label>
              </div>
            </RadioGroup>
            <div className="grid gap-4 mt-6">
              <Input type="text" placeholder="Amount" />
              <Input type="text" placeholder="Recipient" />
              <Button className="w-full">Continue</Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>)
  );
}

function ReceiptIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M4 2v20l2-1 2 1 2-1 2 1 2-1 2 1 2-1 2 1V2l-2 1-2-1-2 1-2-1-2 1-2-1-2 1Z" />
      <path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8" />
      <path d="M12 17.5v-11" />
    </svg>)
  );
}


function SendIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
