/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/nJGcqf9amwb
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"

export function landing() {
  const [transferAmount, setTransferAmount] = useState(250)
  return (
    (<div
      className="flex w-full max-w-5xl items-center justify-between px-4 md:px-6">
      <div className="space-y-4">
        <h1 className="text-5xl font-bold tracking-tighter">sendIN</h1>
        <p className="max-w-md text-muted-foreground md:text-xl/relaxed">
          The fast and secure way to send money to your loved ones.
        </p>
      </div>
      <div className="w-full max-w-md rounded-xl border bg-card p-6 shadow-lg">
        <div className="flex items-center justify-between">
          <h3 className="text-lg font-medium">Transfer</h3>
          <div className="flex items-center gap-2">
            <Button
              variant="ghost"
              size="icon"
              onClick={() => setTransferAmount(transferAmount + 10)}>
              <ChevronUpIcon className="h-4 w-4" />
            </Button>
            <div className="text-2xl font-bold">${transferAmount}</div>
            <Button
              variant="ghost"
              size="icon"
              onClick={() => setTransferAmount(transferAmount - 10)}>
              <ChevronDownIcon className="h-4 w-4" />
            </Button>
          </div>
        </div>
        <div className="mt-4 flex items-center justify-between">
          <h3 className="text-lg font-medium">Receive</h3>
          <div className="text-2xl font-bold">₹15,000</div>
        </div>
        <div className="mt-6 space-y-4">
          <div className="flex items-start gap-2">
            <CheckIcon className="mt-1 h-5 w-5 text-primary" />
            <div>
              <h4 className="text-lg font-medium">Fast and Secure</h4>
              <p className="text-muted-foreground">Your money will be delivered quickly and securely.</p>
            </div>
          </div>
          <div className="flex items-start gap-2">
            <CheckIcon className="mt-1 h-5 w-5 text-primary" />
            <div>
              <h4 className="text-lg font-medium">Low Fees</h4>
              <p className="text-muted-foreground">We offer competitive rates and low fees.</p>
            </div>
          </div>
        </div>
        <div className="mt-6">
          <Button className="w-full">Send Money</Button>
        </div>
      </div>
    </div>)
  );
}

function CheckIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M20 6 9 17l-5-5" />
    </svg>)
  );
}


function ChevronDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m6 9 6 6 6-6" />
    </svg>)
  );
}


function ChevronUpIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m18 15-6-6-6 6" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
